# Generated by Django 3.0.1 on 2020-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191230_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='bs',
            field=models.FloatField(),
        ),
    ]
