# Generated by Django 3.0.1 on 2020-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200103_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='bs',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='bp_high',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='bp_low',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='desease_type',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='hr',
        ),
        migrations.AddField(
            model_name='disease',
            name='ca',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='chol',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='cp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='exang',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='fbs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='oldpeak',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='restecg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='sex',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='slope',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='thal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='thalach',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='trestbps',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='result',
            field=models.BooleanField(),
        ),
    ]
