# Generated by Django 3.0.1 on 2020-02-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200217_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='XGBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='RForest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Nbayes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='LRegression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='KNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='DTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Adaboost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('con_00', models.FloatField()),
                ('con_01', models.FloatField()),
                ('con_10', models.FloatField()),
                ('con_11', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Disease')),
            ],
        ),
    ]
