# Generated by Django 3.0.1 on 2020-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_disease_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaboost',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dtree',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='knn',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lregression',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='nbayes',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rforest',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='svm',
            name='result',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='xgboost',
            name='result',
            field=models.BooleanField(),
        ),
    ]
